// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/account/orders" | "/account/orders/[id]" | "/account/profile" | "/admin" | "/admin/customers" | "/admin/customers/[id]" | "/admin/forgot" | "/admin/forgot-password" | "/admin/inventory" | "/admin/login" | "/admin/orders" | "/admin/orders/[id]" | "/admin/products" | "/admin/products/[id]/edit" | "/admin/products/new" | "/admin/register" | "/cart" | "/categories/[slug]" | "/checkout" | "/contact" | "/login" | "/order-success" | "/products/[slug]" | "/register" | "/search" | "/shop" | "/track-order" | "/wishlist"
type AppRouteHandlerRoutes = "/api/admin/customers" | "/api/admin/customers/[id]" | "/api/admin/inventory/[id]" | "/api/admin/orders" | "/api/admin/orders/[id]" | "/api/admin/products" | "/api/admin/products/[id]" | "/api/admin/upload" | "/api/auth/admin/forgot" | "/api/auth/admin/login" | "/api/auth/admin/logout" | "/api/auth/admin/register" | "/api/auth/admin/reset" | "/api/auth/customer/login" | "/api/auth/customer/logout" | "/api/auth/customer/me" | "/api/auth/customer/register" | "/api/customer/orders" | "/api/customer/orders/[id]" | "/api/customer/profile" | "/api/orders" | "/api/payments/verify" | "/api/products" | "/api/products/[slug]"
type PageRoutes = never
type LayoutRoutes = "/" | "/shop"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account": {}
  "/account/orders": {}
  "/account/orders/[id]": { "id": string; }
  "/account/profile": {}
  "/admin": {}
  "/admin/customers": {}
  "/admin/customers/[id]": { "id": string; }
  "/admin/forgot": {}
  "/admin/forgot-password": {}
  "/admin/inventory": {}
  "/admin/login": {}
  "/admin/orders": {}
  "/admin/orders/[id]": { "id": string; }
  "/admin/products": {}
  "/admin/products/[id]/edit": { "id": string; }
  "/admin/products/new": {}
  "/admin/register": {}
  "/api/admin/customers": {}
  "/api/admin/customers/[id]": { "id": string; }
  "/api/admin/inventory/[id]": { "id": string; }
  "/api/admin/orders": {}
  "/api/admin/orders/[id]": { "id": string; }
  "/api/admin/products": {}
  "/api/admin/products/[id]": { "id": string; }
  "/api/admin/upload": {}
  "/api/auth/admin/forgot": {}
  "/api/auth/admin/login": {}
  "/api/auth/admin/logout": {}
  "/api/auth/admin/register": {}
  "/api/auth/admin/reset": {}
  "/api/auth/customer/login": {}
  "/api/auth/customer/logout": {}
  "/api/auth/customer/me": {}
  "/api/auth/customer/register": {}
  "/api/customer/orders": {}
  "/api/customer/orders/[id]": { "id": string; }
  "/api/customer/profile": {}
  "/api/orders": {}
  "/api/payments/verify": {}
  "/api/products": {}
  "/api/products/[slug]": { "slug": string; }
  "/cart": {}
  "/categories/[slug]": { "slug": string; }
  "/checkout": {}
  "/contact": {}
  "/login": {}
  "/order-success": {}
  "/products/[slug]": { "slug": string; }
  "/register": {}
  "/search": {}
  "/shop": {}
  "/track-order": {}
  "/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/shop": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
